/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Datos;
import model.ModelParcela;

/**
 *
 * @author Pablo
 */
public class Reservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public Datos datos;
    public ArrayList<ModelParcela> parcelas = new ArrayList<ModelParcela>();
    public ModelParcela parce;
    
    public ArrayList<ModelParcela> noselec = new ArrayList<ModelParcela>();
    public ArrayList<ModelParcela> selec = new ArrayList<ModelParcela>();
    
    DefaultListModel modeloder = new DefaultListModel();
    DefaultListModel modeloizq = new DefaultListModel();
    
    
    public Reservas(Datos datos) {
        this.datos = datos;
        initComponents();
               
        // obtengo todas las parcelas almacenadas en Datos
        parcelas = this.datos.getParcelas();
        
        // recorro todas las parcelas
        for(int i = 0; i<parcelas.size(); i++){
            
            // ¿Esta disponible la parcela? 
            if(!parcelas.get(i).getReservado()){
                noselec.add(parcelas.get(i));
            }
        }
        
        actualizarVista();
        
    }

    public void actualizarVista(){
        
        
        
        for(int i = 0; i<noselec.size(); i++){
            
            if(noselec.get(i) != null){
                modeloder.addElement(noselec.get(i).getIdentificador());
            }
        }
        
        listParcelas.setModel(modeloder);
        listParcelasSelect.setModel(modeloizq);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha_ini = new javax.swing.JTextField();
        fecha_sal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listParcelas = new javax.swing.JList<>();
        buttonAdd = new javax.swing.JButton();
        buttonDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listParcelasSelect = new javax.swing.JList<>();
        buttonReserva = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Desde dd/mm/yy");

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Hasta");

        fecha_ini.setBackground(new java.awt.Color(102, 102, 102));
        fecha_ini.setForeground(new java.awt.Color(255, 255, 255));

        fecha_sal.setBackground(new java.awt.Color(102, 102, 102));
        fecha_sal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Parcela   Luz   M2   €/día");

        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("-");

        listParcelas.setBackground(new java.awt.Color(102, 102, 102));
        listParcelas.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listParcelas);

        buttonAdd.setBackground(new java.awt.Color(255, 153, 0));
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setText("-->");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonDel.setBackground(new java.awt.Color(255, 153, 0));
        buttonDel.setForeground(new java.awt.Color(255, 255, 255));
        buttonDel.setText("<--");
        buttonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelActionPerformed(evt);
            }
        });

        listParcelasSelect.setBackground(new java.awt.Color(102, 102, 102));
        listParcelasSelect.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listParcelasSelect);

        buttonReserva.setBackground(new java.awt.Color(255, 153, 0));
        buttonReserva.setText("Reserva");
        buttonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(175, 59, 59));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fecha_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_sal))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDel)
                            .addComponent(buttonAdd))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(buttonReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(buttonAdd)
                                .addGap(28, 28, 28)
                                .addComponent(buttonDel)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonReserva))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu(this.datos);
        this.setVisible(false);
        menu.pack();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservaActionPerformed
        Tiendas tiendas = new Tiendas(datos, fecha_ini.getText(), fecha_sal.getText(), modeloizq);
        this.setVisible(false);
        tiendas.pack();
        tiendas.setLocationRelativeTo(null);
        tiendas.setVisible(true);
    }//GEN-LAST:event_buttonReservaActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        //Al apretar este botón se tendra que actualizar el precio total.
        
        int val;
        val = listParcelas.getSelectedIndex();
        
        String id = modeloder.getElementAt(val).toString();
        modeloder.remove(val);
        modeloizq.addElement(id);
      
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelActionPerformed
        // TODO add your handling code here:
        int val;
        val = listParcelasSelect.getSelectedIndex();
        String id = modeloizq.getElementAt(val).toString();
        modeloizq.remove(val);
        modeloder.addElement(id);
    }//GEN-LAST:event_buttonDelActionPerformed


    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDel;
    private javax.swing.JButton buttonReserva;
    private javax.swing.JTextField fecha_ini;
    private javax.swing.JTextField fecha_sal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listParcelas;
    private javax.swing.JList<String> listParcelasSelect;
    // End of variables declaration//GEN-END:variables

}
